name: setup
description: Sets up development environment
inputs: {}
outputs: {}
runs:
  using: composite
  steps:
    - uses: swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
    - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      with:
        package_json_file: doc/package.json
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        cache: pnpm
        cache-dependency-path: doc/pnpm-lock.yaml
        node-version-file: doc/package.json
    - run: pnpm i --frozen-lockfile
      working-directory: doc
      shell: bash
