name: raviqqe/muffy
description: The static website validator
branding:
  icon: pen-tool
  color: orange
inputs:
  verbose:
    description: Be verbose
    required: false
outputs: {}
runs:
  using: composite
  steps:
    - id: version
      shell: bash
      run: echo version=$(grep '^version = ' < ${{ github.action_path }}/Cargo.toml | grep -o '[0-9.]\+') >> ${{ github.output }}
    - shell: bash
      run: >
        docker run --network host
        --mount type=bind,src=./muffy.toml,dst=/muffy.toml
        raviqqe/muffy:${{ steps.version.outputs.version }}
        check
        ${{ inputs.verbose == 'true' && '--verbose' || '' }}
