[cache]
persistent = true

[sites.default]
roots = []
max_redirects = 8
schemes = ["https"]
statuses = [200]
timeout = "30s"

[sites.default.cache]
max_age = "1w"
stale_while_revalidate = "1w"

[sites.default.retry]
count = 3
factor = 2
interval = { initial = "500ms", cap = "10s" }
statuses = [408, 502, 503, 504]

[sites.default.headers]
user-agent = "Muffy/0.2.0"

[sites.default.validation]
svg = {}
css = true

[sites.main]
extend = "default"
roots = [
  "https://raviqqe.com/",
  "https://raviqqe.com/monza-editor",
  "https://raviqqe.com/muffet",
  "https://raviqqe.com/muffy",
  "https://raviqqe.com/stak",
]
recurse = true

[sites.main.cache]
max_age = "5m"
stale_while_revalidate = "5m"

[sites.main.validation.html]
ignored_attributes = ["data-.*", "sl-.*"]
ignored_elements = [
  "astro-island",
  "div",
  "mobile-starlight-.*",
  "monza-editor",
  "picolight-.*",
  "site-search",
  "sl-.*",
  "starlight-.*",
  "style",
]

[sites.main.validation.svg]
ignored_attributes = ["data-.*"]
# TODO Fix flow elements nested in phrasing elements generated by Mermaid.
ignored_elements = ["p"]

[sites.algo_logic]
extend = "default"
roots = ["https://algo-logic.info/"]
fragments_ignored = true
timeout = "1m"

[sites.crates_io]
extend = "default"
roots = ["https://crates.io/"]
statuses = [200, 403, 404]

[sites.github]
extend = "default"
roots = ["https://github.com/"]
concurrency = 64
fragments_ignored = true

[sites.github.rate_limit]
supply = 10
window = "1s"

[sites.zulip]
extend = "default"
roots = ["https://prog-lang-sys-ja.zulipchat.com/"]
fragments_ignored = true

[sites.broad_200]
extend = "default"
roots = ["https://infoscience.epfl.ch/", "https://www.semanticscholar.org/"]
statuses = [200, 202]

[sites.rate_limited]
extend = "default"
roots = [
  "https://dblp.org/",
  "https://www.lambdanote.com/",
  "https://www.youtube.com/"
]
statuses = [200, 429]

[sites.rate_limited.rate_limit]
supply = 1
window = "1s"

[sites.flaky]
extend = "default"
roots = ["https://gitlab.haskell.org/", "https://zsh.sourceforge.io/"]
timeout = "20s"

[sites.flaky.retry]
count = 5

[sites.fallible]
extend = "default"
roots = ["https://wiki.haskell.org/"]
statuses = [200, 502, 503]

[sites.forbidden]
extend = "default"
roots = [
  "https://armoredcore.fandom.com/",
  "https://dl.acm.org/",
  "https://dragonquest.fandom.com/",
  "https://en.wikipedia.org/wiki/",
  "https://englia.app/",
  "https://jcsites.juniata.edu/",
  "https://mojolang.org/",
  "https://qiita.com/",
  "https://www.npmjs.com/",
  "https://www.oreilly.com/",
  "https://www.researchgate.net/",
]
statuses = [200, 403]

[sites.ignored]
roots = ["https://dblp.org/"]
ignore = true
