name: muffy-cache
description: Caches the persistent Muffy cache
inputs: {}
outputs: {}
runs:
  using: composite
  steps:
    - id: version
      shell: bash
      run: tools/github/version.sh
    - shell: bash
      run: mkdir -p ~/.cache/muffy
    - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: ~/.cache/muffy
        key: muffy-${{ github.workflow }}-${{ github.job }}-${{ strategy.job-index || 0 }}-${{ steps.version.outputs.version }}-${{ github.run_id }}
        restore-keys: muffy-${{ github.workflow }}-${{ github.job }}-${{ strategy.job-index || 0 }}-${{ steps.version.outputs.version }}-
