[cache]
persistent = true

[sites.default]
roots = []
schemes = ["https"]
statuses = [200]

[sites.main]
extend = "default"
roots = ["https://example.com/"]
recurse = true

[sites.external]
extend = "default"

[sites.external.cache]
max_age = "1w"
stale_while_revalidate = "1w"
