name: bench
on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: bench-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
env:
  CARGO_OPTIONS: -j 2
jobs:
  cargo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true
      - uses: ./.github/actions/setup
      - run: cargo bench $CARGO_OPTIONS --features muffy/integration-bench
  codspeed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true
      - uses: ./.github/actions/setup
      - run: cargo install --features vendored-openssl cargo-codspeed
      - run: cargo codspeed build $CARGO_OPTIONS
        # cspell: ignore codspeedhq
      - uses: codspeedhq/action@0ca9cbbf4623b599a6c3ed4fc8a922942705d9f1 # v5.0.2
        with:
          mode: simulation
          run: cargo codspeed run
  bench:
    needs:
      - cargo
      - codspeed
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: for result in ${{ join(needs.*.result, ' ') }}; do [ $result = success ]; done
