name: test
on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: true
      - uses: raviqqe/cargo-cache@4c7db86c0f73cc94a5608ad8b09e7a8e136fd259 # v1.0.4
      - run: cargo build
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: true
      - uses: raviqqe/cargo-cache@4c7db86c0f73cc94a5608ad8b09e7a8e136fd259 # v1.0.4
      - run: cargo test
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: true
      - run: tools/coverage.sh
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          fail_ci_if_error: true
          files: lcov.info
  check_command_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: true
      - uses: raviqqe/cargo-cache@4c7db86c0f73cc94a5608ad8b09e7a8e136fd259 # v1.0.4
      - uses: ./.github/actions/muffy-cache
      - run: cargo run -- --verbose
  check_site_command_test:
    strategy:
      fail-fast: false
      matrix:
        arguments:
          - - --accept-status 202
            - --accept-status 999
            - --ignore https://aclanthology.org/
            - --ignore https://algo-logic.info/
            - --ignore https://crates.io/
            - --ignore https://github.com/raviqqe/stak
            - --ignore https://prog-lang-sys-ja.zulipchat.com/
            - --ignore https://www.gnu.org/software/guile/
            - https://raviqqe.com
          - - --ignore https://codspeed.io/raviqqe/stak
            - --ignore https://r7rs.org/
            - --ignore https://www.gnu.org/software/guile/
            - --header accept:text/html,*/*
            - https://raviqqe.com/stak
          - - --ignore https://crates.io/crates/muffy
            - https://raviqqe.com/muffy
          - - --ignore https://goreportcard.com/
            - https://raviqqe.com/muffet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: true
      - uses: raviqqe/cargo-cache@4c7db86c0f73cc94a5608ad8b09e7a8e136fd259 # v1.0.4
      - uses: ./.github/actions/muffy-cache
      - run: >
          cargo run -- check-site
          --accept-status 200
          --accept-status 403
          --accept-status 429
          --cache
          --concurrency 64
          --header user-agent:Muffy/0.2.0
          --max-age 1w
          --retry-count 5
          --retry-status 408
          --retry-status 500
          --retry-status 502
          --retry-status 503
          --retry-status 504
          --verbose
          ${{ join(matrix.arguments, ' ') }}
  docker_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: true
      - uses: raviqqe/cargo-cache@4c7db86c0f73cc94a5608ad8b09e7a8e136fd259 # v1.0.4
      - id: version
        run: tools/github/version.sh
      - uses: ./.github/actions/muffy-cache
      - uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          tags: raviqqe/muffy:${{ steps.version.outputs.version }}
      - uses: ./.
        with:
          verbose: true
  test:
    needs:
      - build
      - unit_test
      - coverage
      - check_command_test
      - check_site_command_test
      - docker_test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: for result in ${{ join(needs.*.result, ' ') }}; do [ $result = success ]; done
